### PR TITLE
Fixed isxdl translations (German largely, others a bit)

### PR DESCRIPTION
**Pull request by dg9ngf**
The languages fr and pt still need merging into a single file.

### CODE REVIEW

**Comment by stfx** [comment]
Looks good, except for the changes of KB (1024 * byte) -> kB (1000 * byte) as can be seen in isxdl source code: http://sourceforge.net/p/istool/code/HEAD/tree/isxdl/trunk/source/Download.cpp#l585

**Comment by dg9ngf** [comment]
KB is no unit I know of. There is kB which scientifically means 1000 bytes and traditionally means 1024 bytes, and there is KiB which scientifically means 1024 bytes and is commonly still pretty much unknown. KB is sometimes used but wrong.

**Comment by stfx** [comment]
Well traditionally it has been used even tho not completely correct but I would rather have it be consistent as it is hardcoded into isxdl.

https://en.wikipedia.org/wiki/Kilobyte
> In some fields of information technology kilobyte has traditionally also been used to denote 1024 (2^10) bytes, which arises from binary exponentiation common to digital circuitry. In this context the unit symbol K or KB has been common.

**Comment by dg9ngf** [comment]
Well okay, that's just a minor fix. The other wording changes are far more important. I'll update my pull request.

**Comment by dg9ngf** [comment]
isxdl should be fixed, not these translations hacked. Anyway, here's the updated commit.

**Comment by stfx** [comment]
Thanks

**Pull request merged**
